import React,{useEffect,useRef,useState} from "react";
import "./cloud-sync.css";

const CONFIG_KEY="pb_supabase_config_v1", AUTO_KEY="pb_cloud_auto_sync_v1", AUTH_KEY="pb_supabase_auth_v1";
const loadConfig=()=>{try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||"{}")}catch{return{}}};
let loader,sharedClient,sharedClientId="";
const loadSupabase=()=>{if(window.supabase?.createClient)return Promise.resolve(window.supabase);if(loader)return loader;loader=new Promise((resolve,reject)=>{const script=document.createElement("script");script.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js";script.onload=()=>window.supabase?.createClient?resolve(window.supabase):reject(new Error("Supabase did not load."));script.onerror=()=>reject(new Error("Cloud library could not load."));document.head.appendChild(script)});return loader};
const getClient=async config=>{const id=`${config.url}|${config.key}`;if(sharedClient&&sharedClientId===id)return sharedClient;const lib=await loadSupabase();sharedClient=lib.createClient(config.url.trim(),config.key.trim(),{auth:{storage:window.localStorage,storageKey:AUTH_KEY,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});sharedClientId=id;return sharedClient};

export default function CloudSync({data,onRestore}){
 const [savedConfig,setSavedConfig]=useState(loadConfig),[config,setConfig]=useState(loadConfig),[client,setClient]=useState(null),[session,setSession]=useState(null),[initializing,setInitializing]=useState(()=>Boolean(loadConfig().url&&loadConfig().key)),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState("signin"),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[remote,setRemote]=useState(null),[autoSync,setAutoSync]=useState(()=>localStorage.getItem(AUTO_KEY)==="true"),[ready,setReady]=useState(false);
 const dataRef=useRef(data),timer=useRef(null),lastCloud=useRef(""),suppress=useRef(false);
 useEffect(()=>{dataRef.current=data;if(suppress.current){suppress.current=false;return}if(!client||!session||!autoSync||!ready)return;clearTimeout(timer.current);timer.current=setTimeout(()=>{timer.current=null;upload(true)},2500);return()=>clearTimeout(timer.current)},[data,client,session,autoSync,ready]);
 useEffect(()=>{if(!savedConfig.url||!savedConfig.key){setInitializing(false);return}let active=true,subscription;setInitializing(true);getClient(savedConfig).then(async next=>{if(!active)return;setClient(next);const {data:stored,error}=await next.auth.getSession();if(!active)return;if(error)setStatus(`Could not restore cloud login: ${error.message}`);setSession(stored?.session||null);subscription=next.auth.onAuthStateChange((_event,nextSession)=>{if(active)setSession(nextSession)}).data.subscription}).catch(error=>{if(active)setStatus(error.message)}).finally(()=>{if(active)setInitializing(false)});return()=>{active=false;subscription?.unsubscribe()}},[savedConfig.url,savedConfig.key]);
 useEffect(()=>{if(session&&client)inspectCloud();else{setRemote(null);setReady(false)}},[session,client]);
 useEffect(()=>{if(!client||!session||!autoSync||!ready)return;const check=()=>{if(!timer.current)pullIfNewer()};window.addEventListener("focus",check);const interval=setInterval(check,60000);return()=>{window.removeEventListener("focus",check);clearInterval(interval)}},[client,session,autoSync,ready]);
 const saveConfig=()=>{if(!config.url?.startsWith("https://")||!config.key?.trim())return setStatus("Enter the Supabase project URL and publishable key.");const saved={url:config.url.trim(),key:config.key.trim()};localStorage.setItem(CONFIG_KEY,JSON.stringify(saved));setConfig(saved);setSavedConfig(saved);setStatus("Cloud project saved on this device.")};
 const authenticate=async()=>{if(!client)return setStatus("Save the cloud project settings first.");if(!email||password.length<6)return setStatus("Enter an email and a password with at least 6 characters.");setBusy(true);const action=mode==="signup"?client.auth.signUp({email,password,options:{emailRedirectTo:window.location.href.split("#")[0]}}):client.auth.signInWithPassword({email,password});const {data:result,error}=await action;setBusy(false);if(error)return setStatus(error.message);if(mode==="signup"&&!result.session)setStatus("Account created. Check your email to confirm it, then sign in.");else setStatus("Signed in.")};
 const inspectCloud=async()=>{setBusy(true);const {data:row,error}=await client.from("app_snapshots").select("payload,updated_at").eq("user_id",session.user.id).maybeSingle();setBusy(false);if(error)return setStatus(error.message);setRemote(row);lastCloud.current=row?.updated_at||"";if(!row){setStatus("No cloud backup exists yet. Upload this device to create it.");setReady(false)}else{setStatus("Cloud data found. Choose which copy to keep for the first sync.");setReady(false)}};
 const upload=async silent=>{if(!client||!session)return;setBusy(true);const {data:row,error}=await client.from("app_snapshots").upsert({user_id:session.user.id,payload:dataRef.current,updated_at:new Date().toISOString()},{onConflict:"user_id"}).select("updated_at").single();setBusy(false);if(error){setStatus(error.message);return}lastCloud.current=row.updated_at;setRemote({payload:dataRef.current,updated_at:row.updated_at});setReady(true);if(!silent)setStatus("This device is backed up and automatic sync is ready.")};
 const pullIfNewer=async()=>{const {data:row,error}=await client.from("app_snapshots").select("payload,updated_at").eq("user_id",session.user.id).maybeSingle();if(error||!row?.payload||!row.updated_at||row.updated_at<=lastCloud.current)return;suppress.current=true;onRestore(row.payload);lastCloud.current=row.updated_at;setRemote(row);setStatus("Newer cloud changes synced to this device.")};
 const download=async()=>{if(!client||!session)return;setBusy(true);const {data:row,error}=await client.from("app_snapshots").select("payload,updated_at").eq("user_id",session.user.id).single();setBusy(false);if(error)return setStatus(error.message);if(!row?.payload)return setStatus("No cloud backup exists.");if(!confirm("Replace this device's app data with the cloud copy?"))return;suppress.current=true;onRestore(row.payload);lastCloud.current=row.updated_at;setRemote(row);setReady(true);setStatus("Cloud data restored to this device.")};
 const toggleAuto=value=>{setAutoSync(value);localStorage.setItem(AUTO_KEY,String(value));if(value&&ready)setStatus("Automatic sync enabled.");else if(!value)setStatus("Automatic sync paused.")};
 const resetProject=async()=>{if(!confirm("Disconnect this Supabase project from this device? Your local app data will remain."))return;await client?.auth.signOut({scope:"local"});localStorage.removeItem(CONFIG_KEY);localStorage.removeItem(AUTH_KEY);sharedClient=null;sharedClientId="";setSavedConfig({});setConfig({});setClient(null);setSession(null);setReady(false);setStatus("Cloud project disconnected.")};
 const signOut=async()=>{await client?.auth.signOut();setSession(null);setStatus("Signed out.")};
 return <div className="cloud-sync">
  <div className="cloud-status-line"><span className={"cloud-dot "+(session&&ready?"online":session?"waiting":"")}/><div><strong>{session?session.user.email:"Cloud sync not connected"}</strong><span>{status||"Your local app continues working normally."}</span></div></div>
  {initializing&&<div className="cloud-note">Restoring your saved cloud connection...</div>}
  {!initializing&&!client&&<div className="cloud-config"><label>SUPABASE PROJECT URL<input className="field" value={config.url||""} onChange={e=>setConfig({...config,url:e.target.value})} placeholder="https://your-project.supabase.co"/></label><label>PUBLISHABLE KEY<input className="field" value={config.key||""} onChange={e=>setConfig({...config,key:e.target.value})} placeholder="sb_publishable_..."/></label><button className="btn accent" onClick={saveConfig}>SAVE CLOUD PROJECT</button></div>}
  {!initializing&&client&&!session&&<div className="cloud-auth"><button className="btn ghost cloud-change-project" onClick={resetProject}>CHANGE CLOUD PROJECT</button><div className="cloud-mode"><button className={"btn "+(mode==="signin"?"accent":"ghost")} onClick={()=>setMode("signin")}>SIGN IN</button><button className={"btn "+(mode==="signup"?"accent":"ghost")} onClick={()=>setMode("signup")}>CREATE ACCOUNT</button></div><input className="field" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input className="field" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password (6+ characters)"/><button className="btn accent" disabled={busy} onClick={authenticate}>{busy?"WORKING...":mode==="signup"?"CREATE ACCOUNT":"SIGN IN"}</button></div>}
  {session&&<div className="cloud-controls"><div className="cloud-first-choice"><button className="btn accent" disabled={busy} onClick={()=>upload(false)}>{remote?"KEEP THIS DEVICE":"CREATE CLOUD BACKUP"}</button>{remote&&<button className="btn ghost" disabled={busy} onClick={download}>USE CLOUD COPY</button>}</div><label className="cloud-auto"><input type="checkbox" checked={autoSync} disabled={!ready} onChange={e=>toggleAuto(e.target.checked)}/> Automatically back up changes after first sync</label><div className="cloud-secondary"><button className="btn ghost" disabled={busy} onClick={()=>upload(false)}>SYNC NOW</button><button className="btn ghost" disabled={busy||!remote} onClick={download}>RESTORE CLOUD</button><button className="btn ghost" onClick={signOut}>SIGN OUT</button></div></div>}
  <div className="cloud-note">Cloud sync excludes progress photos in this release. Workout, program, metrics, nutrition, settings, and history data are included.</div>
 </div>
}
