import React,{useMemo,useState} from "react";
import "./nutrition.css";
import BarcodeScanner from "./BarcodeScanner.jsx";

const blankFood={name:"",meal:"Breakfast",servings:1,calories:"",protein:"",carbs:"",fat:"",barcode:"",servingLabel:""};
const number=value=>Number(value)||0;
const round=value=>Math.round(value*10)/10;
const dateBefore=date=>{const d=new Date(date+"T12:00:00");d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)};
const dayTotals=day=>(day?.entries||[]).reduce((totals,item)=>{const servings=number(item.servings)||1;totals.calories+=number(item.calories)*servings;totals.protein+=number(item.protein)*servings;totals.carbs+=number(item.carbs)*servings;totals.fat+=number(item.fat)*servings;return totals},{calories:0,protein:0,carbs:0,fat:0});
const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);

function Progress({label,value,target,unit,color}){
 const pct=target?Math.min(100,value/target*100):0,remaining=Math.max(0,target-value);
 return <div className="nutrition-progress"><div><span>{label}</span><strong>{round(value)}<small> / {target} {unit}</small></strong></div><div className="nutrition-track"><i style={{width:pct+"%",background:color}}/></div><div className="nutrition-remaining">{value>target?round(value-target)+" "+unit+" over":round(remaining)+" "+unit+" remaining"}</div></div>
}

export default function NutritionPage({nutrition,onChange,today}){
 const [selectedDate,setSelectedDate]=useState(today),[food,setFood]=useState(blankFood),[saveFood,setSaveFood]=useState(false),[showTargets,setShowTargets]=useState(false),[scannerOpen,setScannerOpen]=useState(false),[barcode,setBarcode]=useState(""),[lookupBusy,setLookupBusy]=useState(false),[lookupStatus,setLookupStatus]=useState("");
 const targets=nutrition.targets,day=nutrition.days[selectedDate]||{entries:[],waterOz:0},totals=useMemo(()=>dayTotals(day),[day]);
 const updateDay=next=>onChange({...nutrition,days:{...nutrition.days,[selectedDate]:next}});
 const addEntry=item=>{if(!item.name.trim())return alert("Enter a food or meal name.");if(!number(item.calories)&&!number(item.protein)&&!number(item.carbs)&&!number(item.fat))return alert("Enter calories or at least one macro.");const entry={...item,id:makeId(),name:item.name.trim(),servings:number(item.servings)||1,calories:number(item.calories),protein:number(item.protein),carbs:number(item.carbs),fat:number(item.fat)};updateDay({...day,entries:[...(day.entries||[]),entry]});if(saveFood){const saved={...entry,id:makeId(),meal:""};onChange({...nutrition,days:{...nutrition.days,[selectedDate]:{...day,entries:[...(day.entries||[]),entry]}},savedFoods:[...nutrition.savedFoods.filter(x=>x.name.toLowerCase()!==saved.name.toLowerCase()),saved]});setSaveFood(false)}setFood(blankFood)};
 const addSaved=item=>{const entry={...item,id:makeId(),meal:"Snack",servings:1};updateDay({...day,entries:[...(day.entries||[]),entry]})};
 const removeEntry=id=>updateDay({...day,entries:(day.entries||[]).filter(x=>x.id!==id)});
 const changeWater=amount=>updateDay({...day,waterOz:Math.max(0,number(day.waterOz)+amount)});
 const copyYesterday=()=>{const prior=nutrition.days[dateBefore(selectedDate)];if(!prior?.entries?.length)return alert("There are no food entries on the previous day.");if(day.entries?.length&&!confirm("Add yesterday's foods to the entries already logged today?"))return;updateDay({...day,entries:[...(day.entries||[]),...prior.entries.map(x=>({...x,id:makeId()}))]})};
 const removeSaved=id=>onChange({...nutrition,savedFoods:nutrition.savedFoods.filter(x=>x.id!==id)});
 const setTarget=(key,value)=>onChange({...nutrition,targets:{...targets,[key]:Math.max(0,number(value))}});
 const lookupBarcode=async raw=>{const code=String(raw||"").replace(/\D/g,"");setScannerOpen(false);setBarcode(code);if(code.length<8)return setLookupStatus("Enter or scan a valid UPC/EAN barcode.");setLookupBusy(true);setLookupStatus("Looking up product...");try{const fields="code,product_name,brands,serving_size,serving_quantity,nutriments,image_front_small_url";const response=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json?fields=${fields}`);if(!response.ok)throw new Error("Food lookup is temporarily unavailable.");const result=await response.json(),product=result.product;if(result.status!==1||!product)throw new Error("Product not found. You can still enter its label manually.");const n=product.nutriments||{},servingQty=number(product.serving_quantity)||number(String(product.serving_size||"").match(/[\d.]+/)?.[0])||100;const nutrient=key=>{const perServing=Number(n[`${key}_serving`]);if(Number.isFinite(perServing))return round(perServing);const per100=Number(n[`${key}_100g`]);return Number.isFinite(per100)?round(per100*servingQty/100):0};const productName=[product.product_name,product.brands].filter(Boolean).join(" - ")||`Barcode ${code}`;setFood(current=>({...current,name:productName,servings:1,calories:nutrient("energy-kcal"),protein:nutrient("proteins"),carbs:nutrient("carbohydrates"),fat:nutrient("fat"),barcode:code,servingLabel:product.serving_size||`${servingQty} g`}));setLookupStatus(`Found ${productName}. Check the serving and nutrition before adding.`)}catch(error){setLookupStatus(error.message||"Product lookup failed. Enter the nutrition label manually.")}finally{setLookupBusy(false)}};
 const recent=Object.entries(nutrition.days).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,7);
 return <div className="nutrition-page">
  <div className="nutrition-title-row"><div><div className="small muted nutrition-kicker">NUTRITION</div><h1>Daily Fuel</h1></div><input className="field nutrition-date" type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}/></div>
  <div className="card calorie-hero"><div><span>CALORIES</span><strong>{Math.round(totals.calories)}</strong><small>{Math.max(0,targets.calories-Math.round(totals.calories))} remaining</small></div><div className="calorie-ring" style={{"--progress":Math.min(100,totals.calories/Math.max(1,targets.calories)*100)+"%"}}><span>{Math.round(totals.calories/Math.max(1,targets.calories)*100)}%</span></div></div>
  <div className="card macro-card"><Progress label="PROTEIN" value={totals.protein} target={targets.protein} unit="g" color="#47C8FF"/><Progress label="CARBS" value={totals.carbs} target={targets.carbs} unit="g" color="#E8FF47"/><Progress label="FAT" value={totals.fat} target={targets.fat} unit="g" color="#FF6B47"/></div>
  <div className="nutrition-actions"><button className="btn ghost" onClick={copyYesterday}>COPY YESTERDAY</button><button className="btn ghost" onClick={()=>setShowTargets(x=>!x)}>{showTargets?"HIDE TARGETS":"EDIT TARGETS"}</button></div>
  {showTargets&&<div className="card nutrition-targets">{[["Calories","calories"],["Protein (g)","protein"],["Carbs (g)","carbs"],["Fat (g)","fat"],["Water (oz)","waterOz"]].map(([label,key])=><label className="small muted" key={key}>{label}<input className="field" type="number" value={targets[key]} onChange={e=>setTarget(key,e.target.value)}/></label>)}</div>}
  <div className="nutrition-section">ADD FOOD</div>
  <div className="card barcode-card"><button className="btn accent barcode-scan-button" onClick={()=>{setLookupStatus("");setScannerOpen(true)}}>SCAN FOOD BARCODE</button><div className="barcode-manual"><input className="field" inputMode="numeric" value={barcode} onChange={e=>setBarcode(e.target.value.replace(/\D/g,""))} placeholder="Or enter barcode number"/><button className="btn ghost" disabled={lookupBusy} onClick={()=>lookupBarcode(barcode)}>{lookupBusy?"LOOKING...":"LOOK UP"}</button></div>{lookupStatus&&<div className="barcode-status">{lookupStatus}</div>}<small>Product data provided by Open Food Facts. Always confirm it matches the package label.</small></div>
  <div className="card food-form"><div className="food-name-row"><input className="field" value={food.name} onChange={e=>setFood({...food,name:e.target.value})} placeholder="Food or meal name"/><select className="field" value={food.meal} onChange={e=>setFood({...food,meal:e.target.value})}>{["Breakfast","Lunch","Dinner","Snack"].map(x=><option key={x}>{x}</option>)}</select></div>{food.servingLabel&&<div className="barcode-serving">Nutrition per serving: <strong>{food.servingLabel}</strong></div>}<div className="food-macro-grid">{[["Servings","servings"],["Calories","calories"],["Protein","protein"],["Carbs","carbs"],["Fat","fat"]].map(([label,key])=><label className="small muted" key={key}>{label}<input className="field" type="number" step="0.1" value={food[key]} onChange={e=>setFood({...food,[key]:e.target.value})}/></label>)}</div><label className="save-food-check small"><input type="checkbox" checked={saveFood} onChange={e=>setSaveFood(e.target.checked)}/> Save this food for quick entry</label><button className="btn accent" onClick={()=>addEntry(food)}>ADD TO DAY</button></div>
  {!!nutrition.savedFoods.length&&<><div className="nutrition-section">SAVED FOODS</div><div className="saved-foods">{nutrition.savedFoods.map(item=><div className="card saved-food" key={item.id}><button className="saved-food-add" onClick={()=>addSaved(item)}><strong>{item.name}</strong><span>{item.calories} cal · P {item.protein} · C {item.carbs} · F {item.fat}</span><i>+ ADD</i></button><button className="saved-food-delete" onClick={()=>removeSaved(item.id)} aria-label={"Delete saved food "+item.name}>×</button></div>)}</div></>}
  <div className="nutrition-section">TODAY'S LOG</div>
  <div className="card food-log">{["Breakfast","Lunch","Dinner","Snack"].map(meal=>{const items=(day.entries||[]).filter(x=>x.meal===meal);if(!items.length)return null;return <div className="meal-group" key={meal}><h3>{meal}</h3>{items.map(item=>{const servings=number(item.servings)||1;return <div className="food-row" key={item.id}><div><strong>{item.name}</strong><span>{servings} serving{servings===1?"":"s"} · {Math.round(item.calories*servings)} cal</span></div><div className="food-row-macros">P {round(item.protein*servings)} · C {round(item.carbs*servings)} · F {round(item.fat*servings)}</div><button onClick={()=>removeEntry(item.id)} aria-label={"Delete "+item.name}>×</button></div>})}</div>})}{!day.entries?.length&&<div className="nutrition-empty">Nothing logged for this day yet.</div>}</div>
  <div className="nutrition-section">WATER</div><div className="card water-card"><div><strong>{number(day.waterOz)} oz</strong><span>of {targets.waterOz} oz</span></div><div><button className="btn ghost" onClick={()=>changeWater(-8)}>−8</button><button className="btn ghost" onClick={()=>changeWater(8)}>+8</button><button className="btn accent" onClick={()=>changeWater(16)}>+16</button></div></div>
  <div className="nutrition-section">RECENT DAYS</div><div className="card nutrition-history">{recent.length?recent.map(([date,value])=>{const t=dayTotals(value);return <button key={date} onClick={()=>setSelectedDate(date)}><span>{new Date(date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})}</span><strong>{Math.round(t.calories)} cal</strong><small>P {Math.round(t.protein)} · C {Math.round(t.carbs)} · F {Math.round(t.fat)}</small></button>}):<div className="nutrition-empty">Your daily nutrition history will appear here.</div>}</div>
  {scannerOpen&&<BarcodeScanner onDetected={lookupBarcode} onClose={()=>setScannerOpen(false)}/>} 
 </div>
}
