import React,{useMemo,useState} from "react";
import "./nutrition.css";

const blankFood={name:"",meal:"Breakfast",servings:1,calories:"",protein:"",carbs:"",fat:"",servingLabel:"1 serving"};
const number=value=>Number(value)||0;
const round=value=>Math.round(value*10)/10;
const dateBefore=date=>{const d=new Date(date+"T12:00:00");d.setDate(d.getDate()-1);return d.toISOString().slice(0,10)};
const dayTotals=day=>(day?.entries||[]).reduce((totals,item)=>{const servings=number(item.servings)||1;totals.calories+=number(item.calories)*servings;totals.protein+=number(item.protein)*servings;totals.carbs+=number(item.carbs)*servings;totals.fat+=number(item.fat)*servings;return totals},{calories:0,protein:0,carbs:0,fat:0});
const makeId=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const COMMON_FOODS=[
 ["Chicken breast, cooked","100 g",165,31,0,3.6],["Ground beef, 90% lean, cooked","100 g",230,28,0,12],["Salmon, cooked","100 g",206,22,0,12],["Large egg","1 egg",72,6.3,.4,4.8],["Egg whites","100 g",52,10.9,.7,.2],
 ["White rice, cooked","1 cup",205,4.3,44.5,.4],["Brown rice, cooked","1 cup",216,5,44.8,1.8],["Oatmeal, cooked","1 cup",166,5.9,28.1,3.6],["Russet potato, baked","1 medium",168,4.6,37,.2],["Sweet potato, baked","1 medium",112,2,26,.1],
 ["Banana","1 medium",105,1.3,27,.4],["Apple","1 medium",95,.5,25,.3],["Blueberries","1 cup",84,1.1,21.5,.5],["Broccoli, cooked","1 cup",55,3.7,11.2,.6],["Avocado","1/2 fruit",120,1.5,6.4,11],
 ["Greek yogurt, nonfat plain","1 cup",130,23,9,0],["Cottage cheese, 2%","1 cup",180,24,10,5],["Whole milk","1 cup",149,7.7,11.7,7.9],["Peanut butter","2 tbsp",190,7,7,16],["Almonds","1 oz",164,6,6,14],
 ["Whey protein powder","1 scoop",120,24,3,2],["Olive oil","1 tbsp",119,0,0,13.5],["Whole wheat bread","1 slice",80,4,14,1],["Flour tortilla, medium","1 tortilla",144,4,24,4],["Black beans, cooked","1 cup",227,15.2,40.8,.9]
].map((x,i)=>({id:"common_"+i,name:x[0],brand:"Common food",servingLabel:x[1],calories:x[2],protein:x[3],carbs:x[4],fat:x[5],source:"Built-in"}));

function Progress({label,value,target,unit,color}){
 const pct=target?Math.min(100,value/target*100):0,remaining=Math.max(0,target-value);
 return <div className="nutrition-progress"><div><span>{label}</span><strong>{round(value)}<small> / {target} {unit}</small></strong></div><div className="nutrition-track"><i style={{width:pct+"%",background:color}}/></div><div className="nutrition-remaining">{value>target?round(value-target)+" "+unit+" over":round(remaining)+" "+unit+" remaining"}</div></div>
}

const offProduct=product=>{
 const n=product.nutriments||{},hasServing=number(n["energy-kcal_serving"])||number(n.proteins_serving)||number(n.carbohydrates_serving)||number(n.fat_serving);
 const per=hasServing?"serving":"100g",name=[product.product_name,product.brands].filter(Boolean).join(" - ");
 return{id:"off_"+(product.code||makeId()),name:name||"Packaged food",brand:product.brands||"Open Food Facts",servingLabel:hasServing?(product.serving_size||"1 serving"):"100 g",calories:round(number(n["energy-kcal_"+per])||number(n.energy_kcal_serving)||0),protein:round(number(n["proteins_"+per])),carbs:round(number(n["carbohydrates_"+per])),fat:round(number(n["fat_"+per])),source:"Open Food Facts"};
};

function FoodLibrary({nutrition,onChange,onUse}){
 const [query,setQuery]=useState(""),[results,setResults]=useState([]),[status,setStatus]=useState(""),[searching,setSearching]=useState(false);
 const builtIn=query.trim().length<2?COMMON_FOODS.slice(0,8):COMMON_FOODS.filter(x=>x.name.toLowerCase().includes(query.trim().toLowerCase()));
 const search=async event=>{event?.preventDefault();const term=query.trim();if(term.length<2)return setStatus("Type at least two characters.");setSearching(true);setStatus("");try{const params=new URLSearchParams({search_terms:term,search_simple:"1",action:"process",json:"1",page_size:"20",fields:"code,product_name,brands,serving_size,nutriments"});const response=await fetch("https://world.openfoodfacts.org/cgi/search.pl?"+params.toString());if(!response.ok)throw new Error();const json=await response.json(),foods=(json.products||[]).map(offProduct).filter(x=>x.name&&x.calories+x.protein+x.carbs+x.fat>0);setResults(foods);setStatus(foods.length?"Packaged-food results from Open Food Facts.":"No packaged foods found. Try a brand or a shorter name.")}catch{setResults([]);setStatus("Online search is unavailable right now. Built-in and saved foods still work.")}finally{setSearching(false)}};
 const useFood=item=>{onUse(item);const recent=[{...item,id:item.id||makeId()},...(nutrition.recentFoods||[]).filter(x=>x.name!==item.name)].slice(0,12);onChange({...nutrition,recentFoods:recent})};
 const cards=(items,empty)=>items.length?<div className="library-results">{items.map(item=><button className="card library-food" key={item.id} onClick={()=>useFood(item)}><div><strong>{item.name}</strong><span>{item.brand} · {item.servingLabel}</span></div><div><b>{Math.round(item.calories)} cal</b><span>P {round(item.protein)} · C {round(item.carbs)} · F {round(item.fat)}</span></div></button>)}</div>:<div className="library-empty">{empty}</div>;
 return <div className="food-library"><form className="library-search" onSubmit={search}><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search chicken, banana, Fairlife..."/><button className="btn accent" disabled={searching}>{searching?"SEARCHING":"SEARCH"}</button></form><div className="library-help">Built-in whole foods appear instantly. Search online for packaged foods and brands.</div>{!!nutrition.recentFoods?.length&&<><div className="library-label">RECENTLY USED</div>{cards(nutrition.recentFoods)}</>}<div className="library-label">{query.trim()?"BUILT-IN MATCHES":"COMMON FOODS"}</div>{cards(builtIn,"No built-in match. Use Search to check packaged foods.")}{(status||results.length>0)&&<><div className="library-label">PACKAGED FOODS</div>{status&&<div className="library-status">{status}</div>}{cards(results,"")}</>}<div className="library-source">Nutrition values are estimates. Check the package label when accuracy is important. Packaged-food data: <a href="https://world.openfoodfacts.org/" target="_blank" rel="noreferrer">Open Food Facts</a>, available under the <a href="https://opendatacommons.org/licenses/odbl/1-0/" target="_blank" rel="noreferrer">ODbL</a>.</div></div>
}

export default function NutritionPage({nutrition,onChange,today}){
 const [selectedDate,setSelectedDate]=useState(today),[food,setFood]=useState(blankFood),[saveFood,setSaveFood]=useState(false),[showTargets,setShowTargets]=useState(false),[showManual,setShowManual]=useState(false);
 const targets=nutrition.targets,day=nutrition.days[selectedDate]||{entries:[],waterOz:0},totals=useMemo(()=>dayTotals(day),[day]);
 const updateDay=next=>onChange({...nutrition,days:{...nutrition.days,[selectedDate]:next}});
 const chooseFood=item=>{setFood({...blankFood,...item,servings:1,meal:food.meal||"Breakfast"});setShowManual(true);setTimeout(()=>document.getElementById("food-entry-form")?.scrollIntoView({behavior:"smooth",block:"center"}),50)};
 const addEntry=item=>{if(!item.name.trim())return alert("Enter a food or meal name.");if(!number(item.calories)&&!number(item.protein)&&!number(item.carbs)&&!number(item.fat))return alert("Enter calories or at least one macro.");const entry={...item,id:makeId(),name:item.name.trim(),servings:number(item.servings)||1,calories:number(item.calories),protein:number(item.protein),carbs:number(item.carbs),fat:number(item.fat)};const nextDay={...day,entries:[...(day.entries||[]),entry]};if(saveFood){const saved={...entry,id:makeId(),meal:""};onChange({...nutrition,days:{...nutrition.days,[selectedDate]:nextDay},savedFoods:[...nutrition.savedFoods.filter(x=>x.name.toLowerCase()!==saved.name.toLowerCase()),saved]});setSaveFood(false)}else updateDay(nextDay);setFood(blankFood);setShowManual(false)};
 const addSaved=item=>{const entry={...item,id:makeId(),meal:"Snack",servings:1};updateDay({...day,entries:[...(day.entries||[]),entry]})};
 const removeEntry=id=>updateDay({...day,entries:(day.entries||[]).filter(x=>x.id!==id)});
 const changeWater=amount=>updateDay({...day,waterOz:Math.max(0,number(day.waterOz)+amount)});
 const copyYesterday=()=>{const prior=nutrition.days[dateBefore(selectedDate)];if(!prior?.entries?.length)return alert("There are no food entries on the previous day.");if(day.entries?.length&&!confirm("Add yesterday's foods to the entries already logged today?"))return;updateDay({...day,entries:[...(day.entries||[]),...prior.entries.map(x=>({...x,id:makeId()}))]})};
 const removeSaved=id=>onChange({...nutrition,savedFoods:nutrition.savedFoods.filter(x=>x.id!==id)});
 const setTarget=(key,value)=>onChange({...nutrition,targets:{...targets,[key]:Math.max(0,number(value))}});
 const recent=Object.entries(nutrition.days).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,7);
 return <div className="nutrition-page">
  <div className="nutrition-title-row"><div><div className="small muted nutrition-kicker">NUTRITION</div><h1>Daily Fuel</h1></div><input className="field nutrition-date" type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}/></div>
  <div className="card calorie-hero"><div><span>CALORIES</span><strong>{Math.round(totals.calories)}</strong><small>{Math.max(0,targets.calories-Math.round(totals.calories))} remaining</small></div><div className="calorie-ring" style={{"--progress":Math.min(100,totals.calories/Math.max(1,targets.calories)*100)+"%"}}><span>{Math.round(totals.calories/Math.max(1,targets.calories)*100)}%</span></div></div>
  <div className="card macro-card"><Progress label="PROTEIN" value={totals.protein} target={targets.protein} unit="g" color="#47C8FF"/><Progress label="CARBS" value={totals.carbs} target={targets.carbs} unit="g" color="#E8FF47"/><Progress label="FAT" value={totals.fat} target={targets.fat} unit="g" color="#FF6B47"/></div>
  <div className="nutrition-actions"><button className="btn ghost" onClick={copyYesterday}>COPY YESTERDAY</button><button className="btn ghost" onClick={()=>setShowTargets(x=>!x)}>{showTargets?"HIDE TARGETS":"EDIT TARGETS"}</button></div>
  {showTargets&&<div className="card nutrition-targets">{[["Calories","calories"],["Protein (g)","protein"],["Carbs (g)","carbs"],["Fat (g)","fat"],["Water (oz)","waterOz"]].map(([label,key])=><label className="small muted" key={key}>{label}<input className="field" type="number" value={targets[key]} onChange={e=>setTarget(key,e.target.value)}/></label>)}</div>}
  <div className="nutrition-section">FIND A FOOD</div><div className="card library-card"><FoodLibrary nutrition={nutrition} onChange={onChange} onUse={chooseFood}/></div>
  <button className="btn ghost manual-toggle" onClick={()=>setShowManual(x=>!x)}>{showManual?"CLOSE FOOD ENTRY":"ENTER FOOD MANUALLY"}</button>
  {showManual&&<><div className="nutrition-section">ADD TO DAY</div><div className="card food-form" id="food-entry-form"><div className="selected-serving">{food.servingLabel||"1 serving"} nutritional values</div><div className="food-name-row"><input className="field" value={food.name} onChange={e=>setFood({...food,name:e.target.value})} placeholder="Food or meal name"/><select className="field" value={food.meal} onChange={e=>setFood({...food,meal:e.target.value})}>{["Breakfast","Lunch","Dinner","Snack"].map(x=><option key={x}>{x}</option>)}</select></div><div className="food-macro-grid">{[["Servings","servings"],["Calories","calories"],["Protein","protein"],["Carbs","carbs"],["Fat","fat"]].map(([label,key])=><label className="small muted" key={key}>{label}<input className="field" type="number" step="0.1" value={food[key]} onChange={e=>setFood({...food,[key]:e.target.value})}/></label>)}</div><div className="serving-preview">{number(food.servings)||1} × {food.servingLabel||"serving"} = {Math.round(number(food.calories)*(number(food.servings)||1))} calories</div><label className="save-food-check small"><input type="checkbox" checked={saveFood} onChange={e=>setSaveFood(e.target.checked)}/> Save this food for quick entry</label><button className="btn accent" onClick={()=>addEntry(food)}>ADD TO DAY</button></div></>}
  {!!nutrition.savedFoods.length&&<><div className="nutrition-section">SAVED FOODS</div><div className="saved-foods">{nutrition.savedFoods.map(item=><div className="card saved-food" key={item.id}><button className="saved-food-add" onClick={()=>addSaved(item)}><strong>{item.name}</strong><span>{item.calories} cal · P {item.protein} · C {item.carbs} · F {item.fat}</span><i>+ ADD</i></button><button className="saved-food-delete" onClick={()=>removeSaved(item.id)} aria-label={"Delete saved food "+item.name}>×</button></div>)}</div></>}
  <div className="nutrition-section">TODAY'S LOG</div>
  <div className="card food-log">{["Breakfast","Lunch","Dinner","Snack"].map(meal=>{const items=(day.entries||[]).filter(x=>x.meal===meal);if(!items.length)return null;return <div className="meal-group" key={meal}><h3>{meal}</h3>{items.map(item=>{const servings=number(item.servings)||1;return <div className="food-row" key={item.id}><div><strong>{item.name}</strong><span>{servings} × {item.servingLabel||"serving"} · {Math.round(item.calories*servings)} cal</span></div><div className="food-row-macros">P {round(item.protein*servings)} · C {round(item.carbs*servings)} · F {round(item.fat*servings)}</div><button onClick={()=>removeEntry(item.id)} aria-label={"Delete "+item.name}>×</button></div>})}</div>})}{!day.entries?.length&&<div className="nutrition-empty">Nothing logged for this day yet.</div>}</div>
  <div className="nutrition-section">WATER</div><div className="card water-card"><div><strong>{number(day.waterOz)} oz</strong><span>of {targets.waterOz} oz</span></div><div><button className="btn ghost" onClick={()=>changeWater(-8)}>-8</button><button className="btn ghost" onClick={()=>changeWater(8)}>+8</button><button className="btn accent" onClick={()=>changeWater(16)}>+16</button></div></div>
  <div className="nutrition-section">RECENT DAYS</div><div className="card nutrition-history">{recent.length?recent.map(([date,value])=>{const t=dayTotals(value);return <button key={date} onClick={()=>setSelectedDate(date)}><span>{new Date(date+"T12:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric"})}</span><strong>{Math.round(t.calories)} cal</strong><small>P {Math.round(t.protein)} · C {Math.round(t.carbs)} · F {Math.round(t.fat)}</small></button>}):<div className="nutrition-empty">Your daily nutrition history will appear here.</div>}</div>
 </div>
}
